### ISSUE TITLE
Benchmark error in the "large_map_parsing" bench

### ISSUE THREAD

**Issue by zamazan4ik** [NoahSchiro/osmgraph#22]
Hi!

When I run `cargo bench` on a local machine in the `osmgraph` root directory, I get the following error:
```
<some lines are skipped>
...
graph_parse             time:   [1.5143 ms 1.5147 ms 1.5152 ms]
Found 5 outliers among 100 measurements (5.00%)
  4 (4.00%) high mild
  1 (1.00%) high severe

thread 'main' panicked at benches/graph.rs:48:10:
Was not able to load json!: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I guess that instead of "manhattan_test.json", the "test.json" should be used but I am not sure.

Environment:
* OS: Fedora 41
* Rustc: 1.82
* `osmgraph` version: `master` branch, `003289931afa4f2371ab78e09e7704ceeb0237ff` commit

Thank you.

**Comment by NoahSchiro** [comment]
Hello! Thanks for raising this point! The reason why this happens is because you need to run `cargo test` before benchmarking. Cargo test will populate a bunch of different test maps.

I suppose I could add a check in the benchmarking scripts to see if the appropriate files are in place before benchmarking against them.

I just want to avoid shipping the OSM data with this code, partially for copyright reasons and partially just to avoid large binaries in the github. 

I will address this when possible!

**Comment by zamazan4ik** [comment]
Ah, gotcha! Thank you!

> I suppose I could add a check in the benchmarking scripts to see if the appropriate files are in place before benchmarking against them.

Before implementing more sophisticated solutions like this you can add a simple note to the README file, something like a small dedicated "Benchmarking" section with a note like "Before running the benchmarks with `cargo bench` you need to run `cargo test` to generate all required test assets". Not ideal but still better than the current way ;)

**Comment by zamazan4ik** [comment]
> The reason why this happens is because you need to run cargo test before benchmarking. Cargo test will populate a bunch of different test maps.

Just tried running `cargo test` - the required file is still not created in the repo

**Comment by NoahSchiro** [comment]
Do tests pass?

**Comment by zamazan4ik** [comment]
Yes. The full run log is here: https://gist.github.com/zamazan4ik/5863fc7c09d1269bf3d904eac9043271

**Comment by NoahSchiro** [comment]
Hey @zamazan4ik I appreciate you putting in this ticket and making me aware of this issue. I have resolved the problem in a PR and it was just merged into master. If you have any other issues, let me know in another ticket!

Sorry this took so long to get to, I was moving this past week.
